export function Copyright() {
	const year = new Date().getFullYear();
	return (
		<footer className="py-6 text-center text-sm text-gray-500 bg-gray-950 space-y-4 px-4">
			<p>&copy; {year} Personal Trainer. All rights reserved.</p>
			<p className="text-xs text-gray-600 max-w-7xl mx-auto">
				<strong>Health & Fitness Disclaimer:</strong> The exercise routines,
				training plans, and dietary recommendations provided by this application
				are generated by artificial intelligence and are intended for
				informational purposes only. They do not constitute medical advice,
				diagnosis, or treatment. Always consult a qualified physician or
				healthcare provider before starting any new exercise program, diet plan,
				or making changes to your existing health regimen. Individual results
				may vary. By using this application, you acknowledge that you assume
				full responsibility for any risks associated with following these
				recommendations and release the developers from any liability for
				injury, illness, or adverse effects.
			</p>
			<p className="text-xs text-gray-600 max-w-7xl mx-auto">
				THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
				OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
				MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
				IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
				CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
				TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
				SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
			</p>
		</footer>
	);
}
